# Диагностический набор шага 0 (Ядро фаза 2, апрель 2026), без изменений
DIAGNOSTIC_PROMPTS = {
    'factual': [
        'The capital of France is',
        'Water boils at a temperature of',
        'The speed of light in vacuum is approximately',
        'The largest planet in our solar system is',
        'DNA stands for',
        'The chemical formula for water is',
        'Mount Everest is located in',
        'The periodic table was created by',
        'Photosynthesis converts sunlight into',
        'The human body has approximately how many bones:',
    ],
    'logical': [
        'If all cats are animals, and all animals breathe, then',
        'The next number in the sequence 2, 4, 8, 16 is',
        'If A is bigger than B, and B is bigger than C, then',
        'A triangle has three sides. A square has four sides. A pentagon has',
        'If it rains, the ground gets wet. The ground is wet. Can we conclude',
        'Every prime number greater than 2 is',
        'If today is Monday, then three days from now is',
        'The contrapositive of "if P then Q" is',
        'In a group of 5 people, the minimum number of handshakes is',
        'If no fish can fly and all sparrows can fly, then',
    ],
    'spatial': [
        'Imagine a cube. The number of faces it has is',
        'If you face north and turn 90 degrees clockwise, you face',
        'A mirror reflects left and right. If you raise your right hand, your reflection raises its',
        'The Earth rotates from west to east, so the sun appears to move from',
        'If you stack three boxes, the bottom box bears the weight of',
        'A circle has how many lines of symmetry:',
        'If you fold a square piece of paper in half diagonally, you get a',
        'The shortest path between two points on a flat surface is',
        'Looking at a clock, when it shows 3:00, the angle between the hands is',
        'If you are inside a room and walk towards the north wall, the south wall is',
    ],
    'emotional': [
        'When someone loses a loved one, they typically feel',
        'The feeling of watching a beautiful sunset can be described as',
        'A child receiving a surprise gift usually reacts with',
        'Being alone in a dark forest at night might make someone feel',
        'Achieving a long-sought goal brings a sense of',
        'Betrayal by a close friend causes feelings of',
        'The emotion associated with seeing injustice is',
        'Nostalgia is the feeling of',
        'When facing an important exam, students often experience',
        'The comfort of returning home after a long journey is',
    ],
    'abstract': [
        'The meaning of justice in a society is',
        'Consciousness can be defined as',
        'The relationship between language and thought is',
        'Freedom without responsibility leads to',
        'The concept of infinity implies that',
        'Truth is different from belief because',
        'The boundary between art and science is',
        'Time is often described as',
        'The nature of mathematical objects is',
        'Identity persists through change because',
    ],
    'code': [
        'To sort a list in Python, you can use',
        'A recursive function must have a',
        'The time complexity of binary search is',
        'In object-oriented programming, inheritance means',
        'A stack data structure follows the principle of',
        'To read a file in Python, you use the',
        'The difference between a list and a tuple in Python is',
        'A hash table provides average lookup time of',
        'In Git, to create a new branch you use',
        'The purpose of a try-except block is to',
    ],
    'ethical': [
        'The trolley problem asks whether it is right to',
        'Privacy in the digital age requires',
        'The responsibility of AI developers includes',
        'When individual rights conflict with collective good,',
        'Informed consent in medical research means',
        'The ethical use of surveillance technology requires',
        'Fairness in algorithmic decision-making means',
        'The right to be forgotten online involves',
        'Environmental responsibility for future generations implies',
        'The ethical implications of genetic editing include',
    ],
    'narrative': [
        'Once upon a time, in a kingdom far away,',
        'The detective examined the crime scene and noticed',
        'As the spaceship approached the unknown planet,',
        'She opened the old letter and read',
        'The last human on Earth heard a knock on the door and',
        'Walking through the ancient forest, he discovered',
        'The scientist made a breakthrough when she realized',
        'After years of searching, the explorer finally found',
        'The robot looked at the sunset and wondered',
        'In the year 2100, humanity had learned to',
    ],
}

ALL_PROMPTS, CATEGORIES = [], []
for cat, ps in DIAGNOSTIC_PROMPTS.items():
    for p in ps:
        ALL_PROMPTS.append(p)
        CATEGORIES.append(cat)
